apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker-1
  namespace: kafka-europe
  labels:
    app: my-mirror-maker-1
spec:
  replicas: 1
  consumer:
    bootstrapServers: us-kafka-bootstrap.kafka-us.svc:9092
    groupId: my-mirror-maker-1
  producer:
    bootstrapServers: europe-kafka-bootstrap.kafka-europe.svc:9092
  whitelist: "us.*"
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 512Mi